### ISSUE TITLE
Bug - HU001 - no hay un mensaje cuando la lista de albumes esta vacia

### ISSUE THREAD

**Issue by hmauryuniandes** [fredyalarcon/ing-sw-apps-moviles-hfmn#45]
Comportamiento Esperado:
Al ingresar a la lista de álbumes, en el caso de que no hayan datos se debe mostrar un mensaje deciendo: "No hay álbumes disponibles" 

Comportamiento Actual: 
el spinner se queda en la pantalla a pesar de que las respuesta del API ya ha terminado.

![image](https://github.com/fredyalarcon/ing-sw-apps-moviles-hfmn/assets/123336163/57cdc605-49e5-4c73-88a1-ae9ab9849c38)

Pasos a reproducir:

1. Ingrese a la aplicación como visitante.
2. selecciones la lista de albumens en el menu principal.

Contexto:
App version: 1
OS: Android 7.0
Maquina: Pixel 1

Informacion Adicional:

**Comment by nparram** [comment]
Evidencia solucion:

[Video](https://github.com/fredyalarcon/ing-sw-apps-moviles-hfmn/assets/78380671/4c7825a0-5ec6-4c7e-b09f-1e85903363e8)
