### ISSUE TITLE
Bug - HU003 - cuando se ingresa por segunda vez a visualizar no muestra las imágenes de los artistas 

### ISSUE THREAD

**Issue by mamunozb** [fredyalarcon/ing-sw-apps-moviles-hfmn#56]
Comportamiento Esperado:
Al ingresar a la lista de artistas debe mostrar las imágenes de cada uno cada vez que se ingrese a la funcionalidad.

Comportamiento Actual:
Al ingresar a la lista de artistas por segunda vez no se muestran las imágenes de los álbumes.
![image](https://github.com/fredyalarcon/ing-sw-apps-moviles-hfmn/assets/124097969/2cfbbfeb-baf0-4c59-a540-965a8ee03c1e)

Pasos a reproducir:

Ingrese a la aplicación como visitante.
selecciones la lista de artistas en el menú principal.
Contexto:
App version: 1
OS: Android 7.0
Maquina: Pixel 1

Información Adicional:

**Comment by fredyalarcon** [comment]
Se soluciona el bug cambiando la librería picasso por Glide.
